apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-v2
spec:
  minReplicas: 3
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoscale-v1-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: cpu
          averageUtilization: 50
        
