apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: antonlarichev/short-app:v1.0
          ports:
            - containerPort: 80
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "100m"