apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - name: front-port
      nodePort: 30001
      port: 80
      targetPort: 80
  selector:
    app: frontend