apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      name: drupal
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: drupal:9.3.9
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html/modules
              name: drupal-pvc
              subPath: modules
            - mountPath: /var/www/html/profiles
              name: drupal-pvc
              subPath: profiles
            - mountPath: /var/www/html/sites
              name: drupal-pvc
              subPath: sites
            - mountPath: /var/www/html/themes
              name: drupal-pvc
              subPath: themes
          ports:
            - containerPort: 80
        - name: init-sites-volume
          image: drupal:9.3.9
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: drupal-pvc
          command: ["/bin/bash", "-c"]
          args: ['cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R']
      volumes:
        - name: drupal-pvc
          persistentVolumeClaim:
            claimName: drupal-pvc