apiVersion: v1
kind: Pod
metadata:
  name: test-config-pod
spec:
  containers:
    - name: test-config-pod
      image: rotorocloud/simple-webapp-rockets
      envFrom:
        - configMapRef:
            name: test-config
        - configMapRef:
            name: test2