# kubectl create configmap test5 --from-env-file test.envs.yaml

HOSTNAME=test-config-pod
F=1
S=2
T=3
TRAEFIK_SERVICE_HOST=10.104.106.228
TRAEFIK_PORT_80_TCP=tcp=/10.104.106.228=0
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_SERVICE_PORT_HTTPS=443
TRAEFIK_SERVICE_PORT=80
TRAEFIK_PORT_80_TCP_PORT=80
TRAEFIK_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp=/10.96.0.1=43
TRAEFIK_PORT_80_TCP_PROTO=tcp
TRAEFIK_PORT_443_TCP=tcp=/10.104.106.228=43
TRAEFIK_PORT_443_TCP_PORT=443
TRAEFIK_PORT_443_TCP_ADDR=10.104.106.228
KUBERNETES_PORT_443_TCP=tcp=/10.96.0.1=43
KUBERNETES_PORT_443_TCP_PROTO=tcp
TRAEFIK_SERVICE_PORT_WEB=80
TRAEFIK_SERVICE_PORT_WEBSECURE=443
TRAEFIK_PORT=tcp=/10.104.106.228=0
TRAEFIK_PORT_80_TCP_ADDR=10.104.106.228
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
LANG=C.UTF-8
GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
PYTHON_VERSION=3.6.12
PYTHON_PIP_VERSION=20.2.4
PYTHON_GET_PIP_URL=https=/github.com/pypa/get-pip/raw/fa7dc83944936bf09a0e4cb5d5ec852c0d256599/get-pip.py
PYTHON_GET_PIP_SHA256=6e0bb0a2c2533361d7f297ed547237caf1b7507f197835974c0dd7eba998c53c
HOME=/root
AA=dssd
BB=dsds
