apiVersion: v1
kind: Service
metadata:
  name: result-app-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30002
      protocol: TCP

  selector:
    app: result-app