apiVersion: batch/v1
kind: Job
metadata:
  name: error-gen-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: error-gen-job
        image: rotorocloud/error-gen
      restartPolicy: Never    
  completions: 1