apiVersion: v1
kind: Pod
metadata:
  name: pv-test
spec:
  containers:
  - name: pv-test
    image: nginx
    ports:
      - containerPort: 80 
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /test/data
        name: pvc-test1
        subPath: volumePath
  volumes:
    - name: n-data
      hostPath:
        path: /var/log
        type: Directory
    - name: pvc-test1
      persistentVolumeClaim:
        claimName: pvc-test1