apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/pv-test/
    type: Directory
    
  persistentVolumeReclaimPolicy: Retain