apiVersion: v1
kind: Pod
metadata: 
  name: logger
spec:
  containers:
    - name: logger
      image: nginx:alpine
      volumeMounts:
        - mountPath: /var/www/nginx
          name: pvc-logger
  volumes:
    - name: pvc-logger
      persistentVolumeClaim:
        claimName: log-claim