apiVersion: v1
kind: Pod
metadata:
  namespace: dev8080
  labels:
    run: secret-busybox
  name: secret-busybox
spec:
  # tolerations:
  #   - key: node-role.kubernetes.io/control-plane
  #     effect: NoSchedule
  #     operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: secret
    volumeMounts:
      - mountPath: /etc/secret-volume
        name: secret-volume
        readOnly: true
    resources: {}
  volumes:
    - name: secret-volume
      secret:
        secretName: secret-key
        
status: {}