apiVersion: v1
kind: Service
metadata:
  name: node-port-nginx
spec:
  type: NodePort
  ports:
  #service port
    - port: 80
  # container port
      targetPort: 80
  # opening port for other pods
      nodePort: 30003
  selector:
    app: nginx-app