apiVersion: v1
kind: Pod
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  containers:
    - name: test-app
      image: hello_world:latest
      resources:
        requests:
          memory: "500Mi"
          cpu: "1000m"
        limits:
          memory: "500Mi"
          cpu: "1000m"
      ports:
        - containerPort: 80