apiVersion: v1
kind: Pod
metadata:
  name: taint-affinity-pod
spec:
  containers:
    - name: taint-affinity
      image: nginx
  tolerations:
    - key: app
      value: all
      operator: Equal
      effect: NoExecute
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: color
                operator: In
                values:
                  - green
