apiVersion: v1
kind: Pod
metadata: 
  name: nodeselector-pod
spec:
  containers:
    - name: nodeselector-pod
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: first
                operator: Exists
                values:
                  - 'true'