apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      name: pg-pod
      labels:
        app: pg
    spec:
      containers:
        - name: pg
          image: postgres:9.4
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust