apiVersion: v1
kind: PersistentVolume
metadata:
  name: time-pv
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  hostPath:
    path: /opt/time
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: time-pvc
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: manual
  resources:
    requests:
      storage: 20Mi
