apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
spec:
  selector:
    name: redis-cluster
  ports:
  - port: 6379
    name: client
  - port: 16379
    name: gossip
  type: ClusterIP