apiVersion: v1
kind: Pod
metadata:
  name: test-security-pod
spec:
  securityContext:
    runAsUser: 1000
    
  serviceAccountName: testAccount
  
  containers:
    - name: test-security-pod
      image: rotorocloud/simple-webapp-rockets
      securityContext:
        capabilities:
          add:
            - SYS_TIME
          