apiVersion: v1
kind: Pod
metadata:
  name: hl-pod-test
  labels:
    app.kubernetes.io/name: hl-pod-test
spec:
  containers:
  - name: hl-pod-test
    image: nginx

  # Должно совпадать с неймом ХлСервиса
  subdomain: db-headless-service
  hostname: nginx-pod

