apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-stateful
spec:
  # Должно совпадать с неймом ХлСервиса

  serviceName: db-headless-service
  # Запускаются по очереди
  # podManagementPolicy: OrderedReady
  # Запускаются вместе
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db-pg
          image: postgres:latest
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/postgresql/data
              subPath: pg-data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: claim-pg
  
  volumeClaimTemplates:
    - metadata:
        name: claim-pg
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
    