apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx-controller
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: http
    - port: 443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: ingress-nginx