apiVersion: v1
kind: Pod
metadata: 
  name: taint-pod
spec:
  containers:
    - name: taint-pod
      image: nginx:alpine
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "test-taint"
      effect: "NoExecute"