apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.app.name }}-ports
      targetPort: {{ .Values.app.port }}
      port: {{ .Values.app.port }}
      protocol: TCP
  selector:
    app: {{ .Values.app.name }}